hp_web/hp_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ui.urls')),
]

hp_web/ui/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.DataScreen.as_view(), name='summary'),
    path('street_trie/', views.fetch_trie, name="street_trie"),
    path('city_trie/', views.fetch_trie, name="city_trie"),
    path('county_trie/', views.fetch_trie, name="county_trie"),
]

hp_web/ui/models.py
from django.db import models
from django.utils import timezone


class Filter(models.Model):
    postcode = models.CharField(max_length=7)
    paon = models.CharField(max_length=128)
    street = models.CharField(max_length=128)
    city = models.CharField(max_length=128)
    county = models.CharField(max_length=64)
    #is_new = models.CharField(max_length=16)
    dwelling_type = models.CharField(max_length=64)
    tenure = models.CharField(max_length=32)
    price_low = models.IntegerField()
    price_high = models.IntegerField()

    date_from = models.DateField()
    date_to = models.DateField()

    def __str__(self):
        return "<Filter: Form>"


class UsageStats(models.Model):
    postcode = models.CharField(max_length=8, null=True)
    paon = models.CharField(max_length=128, null=True)
    street = models.CharField(max_length=128, null=True)
    city = models.CharField(max_length=128, null=True)
    county = models.CharField(max_length=64, null=True)
    #is_new = models.CharField(max_length=16, null=True)
    dwelling_type = models.CharField(max_length=64, null=True)
    tenure = models.CharField(max_length=32, null=True)
    price_low = models.IntegerField(null=True)
    price_high = models.IntegerField(null=True)

    date_from = models.DateField(null=True)
    date_to = models.DateField(null=True)

    response_time = models.FloatField()
    IP_address = models.CharField(max_length=64)
    time_of_submission = models.DateTimeField(null=False, auto_now_add=True)

    def __str__(self):
        s = ''
        for i in ('postcode', 'paon', 'street', 'city', 'county',
                  'dwelling_type', 'tenure', 'price_low', 'price_high',
                  'date_from', 'date_to', 'response_time', 'IP_address'):
            s += f'{i}  {getattr(self, i)}'
        return "<UsageStats: Form>"

hp_web/ui/forms.py
from django import forms

from .models import Filter


def check_pc(postcode):
    """Validator for postcode"""
    if not all((i.isalnum() for i in postcode)):
        bad_char = [i for i in postcode if not i.isalnum()]
        raise forms.ValidationError(f"Postcodes are all alpha-numeric (please remove {''.join(bad_char)})")

    return postcode


def check_street(street):
    """Validator for the street field"""
    valid_char = {'2', 'c', 'x', 'j', '4', '1', '&', 'k', 'n', '5', 'f', ' ', 'b', 'l',
                  "'", 'z', '7', 'u', 'p', '-', 'e', 'h', '9', '3', ',', 'r', 'o', 'd',
                  '(', 's', '8', 'i', 'a', 'm', 'v', '0', '6', 't', 'y', 'w', ')', '.',
                  'q', 'g'}
    if not all(i.lower() in valid_char for i in street):
        raise forms.ValidationError("Unknown characters in the street field")
    return street


def check_city(city):
    """Validator for the city field"""
    valid_char = {'c', '-', 'x', 'e', 'h', 'j', 'k', 'r', 'o', 'd', 's', 'i', 'n', 'f',
                  ' ', 'm', 'a', 'v', 'b', 'l', 't', 'y', 'w', "'", 'z', '.', 'u', 'q',
                  'p', 'g'}
    if not all(i.lower() in valid_char for i in city):
        raise forms.ValidationError("Unknown characters in the city field")
    return city


def check_county(county):
    """Validator for the county field"""
    valid_char = {'c', '-', 'x', 'e', 'h', ',', 'k', 'r', 'o', 'd', 's', 'n', 'i', 'f',
                  ' ', 'm', 'a', 'v', 'b', 'l', 't', 'y', 'w', 'u', 'p', 'g'}
    if not all(i.lower() in valid_char for i in county):
        raise forms.ValidationError("Unknown characters in the county field")
    return county


class FilterForm(forms.ModelForm):

    class Meta:
        model = Filter
        fields = ('postcode', 'street', 'city',
                  'county', 'price_low', 'price_high',
                  'date_from', 'date_to', 'dwelling_type',
                  'tenure', 'paon')

    def __init__(self, *args, **kwargs):
        """Set all fields to not-required"""
        super().__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].required = False

        # Validate the postcode field
        pc_field = self.fields['postcode']
        pc_field.validators.append(check_pc)

        # Validate the street field
        st_field = self.fields['street']
        st_field.validators.append(check_street)

        # Validate the city field
        city_field = self.fields['city']
        city_field.validators.append(check_city)

        # Validate the county field
        county_field = self.fields['county']
        county_field.validators.append(check_county)

hp_web/ui/views.py
from datetime import datetime
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View

import json
import numpy as np
import os
import pandas as pd
import requests as rq
import time
import yaml

from .forms import FilterForm
from . import orm

import hp_data as hpd


def fetch_trie(request):
    """View to fetch the trie requested via AJAX and send it as json"""
    data = {}
    if request.method == "POST":
        loc = request.POST.get('_loc', '')
        tries = {'street': hpd.street_trie, 'city': hpd.city_trie,
                 'county': hpd.county_trie, '': {}}
        pre = request.POST.get('_prefix', '')
        if len(pre) > 1:
            data = tries[loc]
            for letter in pre:
                data = data.get(letter.lower(), {})
    return JsonResponse(data)


class BaseSelectorScreen(View):
    """A base screen that handles selectors that other screens can inherit from"""
    _str_keys = {'city', 'street', 'postcode', 'county', 'paon'}
    _checks = {'is_new': 2, 'tenure': 2, 'dwelling_type': 2}

    def _create_selectors(self, request):
        """Will create the selectors that will be sent to the controller to get back data

        The selectors are created from the front-end form.
        """
        selectors = {}
        for key in request.POST:
            if key.startswith('date_'):
                selectors[key] = datetime.strptime(request.POST[key], '%Y-%m-%d')

            elif key in self._str_keys and request.POST[key]:
                selectors[key] = str(request.POST[key])

            elif key.endswith('_checks'):
                val = request.POST.getlist(key)
                k = key[:-7]
                if len(val) < self._checks[k]:
                    selectors[k] = val

            elif key.startswith('price_'):
                low = int(request.POST['price_low'])
                high = int(request.POST['price_high'])
                if low > 0:
                    selectors['price_low'] = low
                if high < 2.5e6:
                    selectors['price_high'] = high

        # Now prep the dates
        min_date = hpd.DATA_STATS['min_date']
        max_date = hpd.DATA_STATS['max_date']
        if 'date_to' in selectors and selectors['date_to'] >= max_date:
            selectors.pop('date_to')
        if 'date_from' in selectors and selectors['date_from'] <= min_date:
            selectors.pop('date_from')
        if 'date_to' in selectors:
            selectors['date_to'] = selectors['date_to'].strftime('%Y-%m-%d')
        if 'date_from' in selectors:
            selectors['date_from'] = selectors['date_from'].strftime('%Y-%m-%d')

        # Prep tenure
        if 'tenure' in selectors:
            # Selecting everything -just don't filter by it
            if len(selectors['tenure']) == 2:
                selectors.pop('tenure')
            else:
                selectors['tenure'] = selectors['tenure'][0]

        return selectors


class DataScreen(BaseSelectorScreen):
    """View for the general data screen"""
    _max_data_len = None
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._max_data_len = int(1e5)


    def get(self, request):
        """No submissions etc"""
        form = FilterForm(request.POST)
        return render(request, 'ui/summary.html', {'form': form,
                                                   'form_data': {},
                                                   'table': {},
                                                   'err_msg': ''})

    def post(self, request):
        """After submitting form"""
        form = FilterForm(request.POST)
        form_data = {f: request.POST[f] for f in form.fields}
        ret_obj = {'form': form, 'form_data': form_data, 'err_msg': ''}

        if form.is_valid():
            selectors = self._create_selectors(request)
            t1 = time.time()
            ret_data = rq.post('http://0.0.0.0:8008', json={**selectors}).json()
            data_retreival_time = time.time() - t1

            orm.record_usage_stats(selectors, request.POST.get('IP'), data_retreival_time)

        if isinstance(ret_data, int):
            if ret_data == 1:
                ret_obj['err_msg'] = 'No data for current selection, please try a different search'
            else:
                ret_obj['err_msg'] = 'Internal Server Error'
        else:
            ret_obj['data'] = ret_data

        return render(request, 'ui/summary.html', ret_obj)

hp_web/ui/templates/ui/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>What did they pay?</title>

		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- W3.CSS etc -->
		<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
		<script src="https://www.w3schools.com/lib/w3.js"></script>
		<!-- Icons -->
		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
		<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

		<!-- jquery -->
		<script src="https://code.jquery.com/jquery-3.6.0.min.js" 
				integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" 
				crossorigin="anonymous"></script>

		<!-- Own CSS -->
		<link rel="stylesheet" href="{% static 'css/ui.css' %}">
		<link rel="stylesheet" href="{% static 'css/slider.css' %}">

    </head>
    
	<body>
		{% block content %}
		{% endblock %}
	</body>

	<footer>
		<script type='text/javascript' src="{% static 'js/slider.js' %}"></script>
		<script>
			setSlidersFromForm(form_data);
		</script>

	</footer>
</html>

hp_web/ui/templates/ui/base_sidebar.html
{% extends 'ui/base.html' %}
{% load static %}


{% block content %}
	<script type="text/javascript" src="{% static 'js/sidebar.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/sidebar.css' %}">

	<!-- Sidebar -->
	<div class="w3-bar-block my-sidebar" id='my-sidebar' style='display: none'>
		<form method="POST" class="post-form">
			{% csrf_token %}
			<input type="submit" class="w3-btn w3-ripple w3-right submit-button" style="margin-bottom: 0; margin-right: 5px; margin-top: 5px;"
			       onclick='set_hamburger_mode(true)'>

			<!-- Postcode -->
			<script>
				function remove_spaces(id) {
					const new_val = document.getElementById(id).value.replace(/\s+/g, '').toUpperCase();
					document.getElementById(id).value = new_val;
				};
			</script>
			<label class="w3-bar-item w3-left" style="margin-top: -15px"><b>Postcode</b></label>
			<input class="w3-bar-item w3-input mtext-field" type="text" name="postcode" id="id_postcode" maxlength="7"
				   autocomplete="chrome-off" oninput="remove_spaces('id_postcode');">

			<!-- House Number/Name -->
			<label class="w3-bar-item"><b>House Num/Name</b></label>
			<input class="w3-bar-item w3-input mtext-field" type="text" name="paon" id="id_paon" maxlength="128">
			
			<!-- Street -->
			<label class="w3-bar-item"><b>Street</b></label>
			<input class="w3-bar-item w3-input mtext-field" type="text" name="street" id="id_street" maxlength="70"
				   autocomplete="chrome-off" oninput='autocomplete_streets()'>
			<div class="mtext-field options_dropdown" id="street_dropdown"></div>
			
			<!-- City -->
			<label class="w3-bar-item"><b>City</b></label>
			<input class="w3-bar-item w3-input mtext-field" type="text" name="city" id="id_city" maxlength="70"
				   autocomplete="chrome-off" oninput='autocomplete_cities()'>
			<div class="mtext-field options_dropdown" id="city_dropdown"></div>

			<!-- County -->
			<label class="w3-bar-item"><b>County</b></label>
			<input class="w3-bar-item w3-input mtext-field" type="text" name="county" id="id_county" maxlength="40"
				   autocomplete="chrome-off" oninput='autocomplete_counties()'>
			<div class="mtext-field options_dropdown" id="county_dropdown"></div>

			<!-- Price -->
			<label class="w3-bar-item"><b>Price Range</b></label>
            <div class="slider-track mtext-field"></div>
            <input class="mtext-field" type="range" min="0" max="100" value="0" id="slider-1" oninput="slideOne()">
            <input class="mtext-field" type="range" min="0" max="100" value="100" id="slider-2" oninput="slideTwo()">
			<input style="display: none" id="id_price_low" name="price_low" type="number">
			<input style="display: none" id="id_price_high" name="price_high" type="number">
			<div class="w3-bar-item">
				<span style="float: left; color: #fff;/*ef5040;*/"><b id="slider-val-1">0</b></span> 
				<span style="float:right; color: #fff;/*50bf40;*/"><b id="slider-val-2">>2.5m</b></span>
			</div>
			<br>

			<!-- Dates -->
			<label class="w3-bar-item"><b>From</b></label>
			<input class="mtext-field w3-input" type="date" name="date_from" id="id_date_from" value="2018-01-01" min="1995-01-01">
			<label class="w3-bar-item"><b>To</b></label>
			<input class="mtext-field w3-input" type="date" name="date_to" id="id_date_to" min="1995-01-01">
			<script type="text/javascript">
				// Set the to date
				let elm_to = document.getElementById('id_date_to');
				const currDT = new Date();
				const max_date_str = currDT.getFullYear() + "-" 
	                                + String(currDT.getMonth()+1).padStart(2,'0') + "-" 
		                            + String(currDT.getDate()).padStart(2, '0');
				elm_to.value = max_date_str;
				elm_to.max = max_date_str;

				// Set the from date
				const three_years = new Date('2021/01/01') - new Date('2018/01/01');
				let elm_from = document.getElementById('id_date_from');
				const three_years_ago = new Date(currDT - three_years);
				elm_from.value = three_years_ago.getFullYear() + "-" 
							+ String(three_years_ago.getMonth()+1).padStart(2,'0') + "-" 
							+ String(three_years_ago.getDate()).padStart(2, '0');
				elm_from.max = max_date_str;
			</script>


			<!-- Dwelling Type -->
			<label class="w3-bar-item" style="margin-top: 6px"><b>Dwelling Type</b></label>
			<input class="w3-check" type="checkbox" name="dwelling_type_checks" checked style="margin-left: 15px;"
				   onchange="set_form_check_value('dwelling_type')" value='Residential'>
			<label>Residential</label>
			<br>
			<input class="w3-check" type="checkbox" name="dwelling_type_checks" style="margin-left: 15px" 
				   onchange="set_form_check_value('dwelling_type')" value='Commercial'>
			<label>Commericial</label>
			<input style="display: none" type="text" id="id_dwelling_type" name="dwelling_type" value="Residential">

		<!--	Is New Build?
			<label class="w3-bar-item"><b>New Build</b></label>
			<input class="w3-check" type="checkbox" name="is_new_checks" value="is_new" style="margin-left: 15px" checked
				   onchange="set_form_check_value('is_new')">
			<label>Yes</label>
			<input class="w3-check" type="checkbox" name="is_new_checks" value="not_new" checked
				   onchange="set_form_check_value('is_new')">
			<label>No</label>
			<input style="display: none" type="text" id="id_is_new" name="is_new" value="is_new,not_new"> 
		-->

			<!-- Freehold or Leasehold? -->
			<label class="w3-bar-item"><b>Tenure</b></label>
			<input class="w3-check" type="checkbox" name="tenure_checks" value="Freehold" style="margin-left: 15px" checked
				   onchange="set_form_check_value('tenure')">
			<label>Freehold</label>
			<br>
			<input class="w3-check" type="checkbox" name="tenure_checks" value="Leasehold" style="margin-left: 15px" checked
				   onchange="set_form_check_value('tenure')">
			<label>Leasehold</label>
			<input style="display: none" type="text" id="id_tenure" name="tenure" value="Freehold,Leasehold">
			<input style="display: none" type="text" id="id_IP" name="IP" value="">
		</form>
	</div>

	<script type="text/javascript">
		const MAX_SCREEN_WIDTH_HAMBURGER = 800;
		/* Will toggle the hamburger menu on or off */
		function set_hamburger_mode(set_state) {
			const sidebar_div = document.getElementById('my-sidebar');
			const sdb_cnt_div = document.getElementById('sidebar-content');
			const hbgr_icon = document.getElementById('hamburger-icon-li');
			const overlay = document.getElementById('grey-overlay');
			
			// If the window has a desktop width then never show the hamburger
			if (window.innerWidth >= MAX_SCREEN_WIDTH_HAMBURGER) {
				set_state = false;
			}

			// Hide sidebar
			if (set_state) {
				sidebar_div.style.display = 'none';
				sdb_cnt_div.style.width = '100%';
				sdb_cnt_div.style.left = '0px';
				hbgr_icon.style.display = 'block';
				overlay.style.display = 'none';
			} 
			// Show sidebar
			else {
				sidebar_div.style.display = 'block';
				sdb_cnt_div.style.width = 'calc(100% - 190px)';
				sdb_cnt_div.style.left = '190px';
				hbgr_icon.style.display = 'none';
				overlay.style.display = 'block';
				//overlay.style.display = '190px';
			}
			if (window.innerWidth >= MAX_SCREEN_WIDTH_HAMBURGER) {
				overlay.style.display = 'none';
			}
		}

		// Set the form data
		const form_data={{form_data|safe}};
		populate_fields(form_data);
		add_dropdown_elements();
	</script>
	<script type="text/javascript" src="{% static 'js/categories.js' %}"></script>

	<!-- Main Body -->
	<div class="w3-container sidebar_content" id='sidebar-content'>
		<div style='width: 100%; height: 100%; z-index: 2; background-color: #000; opacity: 0.5; position: absolute; display: none;'
		 	 id='grey-overlay' onclick='set_hamburger_mode(true)'></div>
		<ul class='navbar-ul' id='navbar'>
			<li class='navbar-li' id='hamburger-icon-li'>
				<div id="hamburger-icon" onclick='set_hamburger_mode(false)'>
					<svg height="50" width="50">
						<line x1="15%" y1="27%" x2="85%" y2="27%" class='hamburger_line' />
						<line x1="15%" y1="50%" x2="85%" y2="50%" class='hamburger_line' />
						<line x1="15%" y1="73%" x2="85%" y2="73%" class='hamburger_line' />
					</svg>
				</div>
			</li>
		</ul>
		<div class="w3-content" style="width: 100%">
			{% block main_content %}
			{% endblock %}
		</div>
		<div class="w3-container" style='height: calc(100% - 60px)'>
			<br>
			Contains HM Land Registry data © Crown copyright and database right 2021. This data is licensed under the Open Government Licence v3.0.
		</div>
	</div>

	<script>
		// Get user IP
		var IP = $.getJSON('https://api.ipify.org?format=jsonp&callback=?', function(data) {
			document.getElementById('id_IP').value = data['ip'];
		});

		set_hamburger_mode(false);
		window.addEventListener("resize", function() {
			set_hamburger_mode(true);
		})

	</script>

{% endblock %}

hp_web/ui/templates/ui/summary.html
{% extends 'ui/base_sidebar.html' %}
{% load static %}



{% block main_content %}
<p class='err_msg'>{{err_msg}}</p>

<script type='text/javascript' src="{% static 'js/utils.js' %}"></script>
<script type='text/javascript' src="{% static 'js/table.js' %}"></script>
<script type='text/javascript' src="{% static 'js/plot.js' %}"></script>
<!--
<script type='text/javascript' src="{% static 'js/map.js' %}"></script>
-->
<script src='https://cdn.plot.ly/plotly-2.9.0.min.js'></script>

<link rel="stylesheet" href="{% static 'css/table.css' %}">

<div id="root_container_div" class="w3-container">
	<div id="content_div">
		<div id='id_table_div' style='display: none'>
			<table id="id_summary_table"></table>
		</div>

		<div id='id_plot_div' style='display: none'>
			<p id='id_plot_explain' style='margin: 0'></p>
		</div>

		<!--<div id='id_map_div' style='display: none'>
			<p id='id_map_explain' style='margin: 0'></p>
		</div> 
		-->
	</div>
</div>

<script>
//	const False=false;
//	const True=true;
	{% autoescape off %}
	{% if data %}
		const input_data = {{data}};
	{% else %}
		const input_data = {};
	{% endif %}
	{% endautoescape %}

	// Add navbar items
	const navbar = document.getElementById('navbar');
	let navbar_obj = {'table': {}, 'plot': {}}; //, 'map': {}};
	for (let elm_name in navbar_obj) {
		const li = document.createElement('li');
		li.className = 'navbar-li';
		const a = document.createElement('a');
		a.className = 'navbar-a';
		a.innerHTML = title_case(elm_name);
		a.setAttribute('onclick', `switchView('${elm_name}')`);

		li.appendChild(a);
		navbar.appendChild(li);
		navbar_obj[elm_name]['a_obj'] = a;
		navbar_obj[elm_name]['li_obj'] = li;

	}
	navbar_obj['table']['a_obj'].className += ' active ';


	//////////////////////////////////////////
	////// Handle Switch Between Pages ///////
	//////////////////////////////////////////
	/* Will create the table page in a div
     * 
     * Args:
     *    - div_name: <str> the id of the div to create the table in
     *    - table_data: <object> the data in the table of the form: {'columns': [...],
    																 'data': [['col1', 'col2', ...],
    																		  ['col1', 'col2', ...],
    																		   ...]}
						(from `decode_huffman` function)
	 */
	function create_table_page(div_name, table_data) {
		// Create the table
		if (Object.entries(table_data).length > 0 & table_data['data'].length > 0) {
			window.table = new Table(table_data, 'id_table_div', 'id_summary_table');
			window.table.show();
			window.table.create_table();
			/* Add more to table on scroll down */
			const sidebar_div = document.getElementById('sidebar-content');
			sidebar_div.addEventListener("scroll", function() {
				if (percentageScrolled() > 0.9) {
					window.table.draw_next_N_rows(20);
				}
			})
		}

		_handle_navbar_active_switcher('table');
		window.current_element = window.table;
	}

	/* Will handle which tab is set to be active in the navbar
	*/
	function _handle_navbar_active_switcher(name) {
		for (i in navbar_obj) {
			navbar_obj[i]['a_obj'].className = navbar_obj[i]['a_obj'].className.replace(' active', '');
		}
		window.navbarElement = name;

		if (window.current_element) {
			window.current_element.hide();
		}
		localStorage.setItem('navbarElement', name);
		if (navbar_obj[name]['a_obj'].className.search(' active ') === -1) {
			navbar_obj[name]['a_obj'].className += ' active ';
		}
	}

	/* Will create the plot page in a div
     * 
     * Args:
     *    - div_name: <str> the id of the div to create the table in
     *    - table_data: <object> the data in the table of the form: {'columns': [...],
    																 'data': [['col1', 'col2', ...],
    																		  ['col1', 'col2', ...],
    																		   ...]}
						(from `decode_huffman` function)
	 */
	function create_plot_page(div_name, table_data) {
		if (Object.entries(table_data).length > 0 & table_data['data'].length > 0) {
			window.plot = new Plot(table_data, 'id_plot_div');
			window.plot.plot('date_transfer', 'price');
			window.plot.show();

			document.getElementById('id_plot_explain').innerHTML = "The chart above shows the median price, along with each 10<sup>th</sup> percentile in increasingly faded colours.";
		}
		_handle_navbar_active_switcher('plot');
		window.current_element = window.plot;
	}

	/* Will create the map page in a div
     * 
     * Args:
     *    - div_name: <str> the id of the div to create the table in
     *    - table_data: <object> the data in the table of the form: {'columns': [...],
    																 'data': [['col1', 'col2', ...],
    																		  ['col1', 'col2', ...],
    																		   ...]}
						(from `decode_huffman` function)
	 */
	function create_map_page(div_name, table_data) {
		if (Object.entries(table_data).length > 0 & table_data['data'].length > 0) {
			window.map = new Map(table_data, 'id_map_div');
			window.map.draw();
			window.map.show();
		}
		_handle_navbar_active_switcher('map');
		window.current_element = window.map;
	}
	
	{% if data.length != 0 %}
		table_data = decode_huffman(input_data);
		const NE = localStorage.getItem('navbarElement') || window.navbarElement || 'table';
		const page_func = {'table': function () {create_table_page('content_div', table_data)},
						   'plot': function () {create_plot_page('content_div', table_data)},
						   'map': function () {create_map_page('content_div', table_data)},
		};
		page_func[NE]();
	{% endif %}

	/* Will switch between the Table View and the Plot View */
	function switchView(navbar_item) {
		switch (navbar_item) {
			case 'table':
				create_table_page('content_div', table_data);
				break;
			case 'plot':
				create_plot_page('content_div', table_data);
				break;
			case 'map':
				create_map_page('content_div', table_data);
			default:
				console.log(`No case ${navbar_item}`);
		}
		window.navbarElement = String(navbar_item).toLowerCase();
	}

</script>


{% endblock %}